uploads = []
generated = []

[[outputs]]
id = "FJHKxHs78FQ732dIEzfAd"
uri = "file://vercel.json"
type = "unspecified"
title = "vercel.json"

[[outputs]]
id = "iLwGg98Ia7Ybv0vZ0RFlO"
uri = "file://lilac-gifts-website.tar.gz"
type = "unspecified"
title = "ملفات الموقع جاهزة للنشر على Netlify"

[[outputs]]
id = "uN7xTlfFR7MHs6bMyroUX"
uri = "file://netlify-deploy.tar.gz"
type = "unspecified"
title = "📁 مجلد المصدر (للرفع على GitHub + Netlify)"

[[outputs]]
id = "PbK36tG3Pg_fJl84wJQSZ"
uri = "file://lilac-dist-ready.tar.gz"
type = "unspecified"
title = "🌷 الموقع الجديد - مع لوحة تحكم"

[[outputs]]
id = "tRLsqe0zWF_iA8q7lZ3CP"
uri = "file://lilac-gifts-complete.tar.gz"
type = "unspecified"
title = "📦 ملف المصدر الكامل"
